version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: issue_tracker
      POSTGRES_USER: judy
      POSTGRES_PASSWORD: judy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: beellage_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/issue_tracker
      SPRING_DATASOURCE_USERNAME: judy
      SPRING_DATASOURCE_PASSWORD: judy
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
